on:
  - push
  - pull_request

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        directory: [client, server]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: ./${{ matrix.directory }}/pnpm-lock.yaml

      - name: "Install dependencies"
        working-directory: ./${{ matrix.directory }}
        run: pnpm install

      - name: "Format"
        working-directory: ./${{ matrix.directory }}
        run: pnpm format

      - name: "Commit formatting changes"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style(ci): fix formatting"
          add_options: "-A"
